const ErrorCode = {
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_LOCKED: "WALLET_LOCKED",
  WALLET_IS_INACTIVE: "WALLET_IS_INACTIVE",
  DEBIT_FAILED: "DEBIT_FAILED",
  CREDIT_FAILED: "CREDIT_FAILED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND", // Device is absent from sfc registry
  DEVICE_IS_ACTIVE: "DEVICE_IS_ACTIVE", // Device is linked to an account
  DEVICE_IS_INACTIVE: "DEVICE_IS_INACTIVE", // Device is sfc registered, but not claimed
  DEVICE_DISABLED: "DEVICE_DISABLED", // Device is disabled by user action
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  PHONE_NUMBER_ALREADY_EXISTS: "PHONE_NUMBER_ALREADY_EXISTS",
  SELF_PAYMENT_NOT_ALLOWED: "SELF_PAYMENT_NOT_ALLOWED",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
  TRANSACTION_ALREADY_PROCESSED: "TRANSACTION_ALREADY_PROCESSED",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  CURRENCY_NOT_VALID: "CURRENCY_NOT_VALID",
  LEDGER_ACCOUNT_NOT_FOUND: "LEDGER_ACCOUNT_NOT_FOUND",
  LEDGER_ENTRY_NOT_FOUND: "LEDGER_ENTRY_NOT_FOUND",
  PAYMENT_REQUEST_EXPIRED: "PAYMENT_REQUEST_EXPIRED",
  PAYMENT_REQUEST_ERROR: "PAYMENT_REQUEST_ERROR",
  PAYMENT_REQUEST_NOT_FOUND: "PAYMENT_REQUEST_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FIREBASE_ERROR: "FIREBASE_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  CONFLICT: "CONFLICT",
  FORBIDDEN: "FORBIDDEN",
  NOTFOUND: "NOTFOUND",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export default ErrorCode;
