const ErrorCode = {
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_LOCKED: "WALLET_LOCKED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND", // Device is absent from sfc registry
  DEVICE_IS_ACTIVE: "DEVICE_IS_ACTIVE", // Device is linked to an account
  DEVICE_IS_INACTIVE: "DEVICE_IS_INACTIVE", // Device is sfc registered, but not claimed
  DEVICE_DISABLED: "DEVICE_DISABLED", // Device is disabled by user action
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  INVALID_PHONE_NUMBER: "INVALID_PHONE_NUMBER",
  PHONE_NUMBER_ALREADY_EXISTS: "PHONE_NUMBER_ALREADY_EXISTS",
  SELF_PAYMENT_NOT_ALLOWED: "SELF_PAYMENT_NOT_ALLOWED",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
  TRANSACTION_ALREADY_PROCESSED: "TRANSACTION_ALREADY_PROCESSED",
  PAYMENT_INTENT_EXPIRED: "PAYMENT_INTENT_EXPIRED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export default ErrorCode;
